_target_: atria_transforms.core.tf_composer.ImageTransformsComposer
apply_path: image
configs:
- _target_: atria_registry.registry_config.RegistryConfig
  name: image/resize
- _target_: atria_registry.registry_config.RegistryConfig
  name: image/to_tensor
- _target_: atria_registry.registry_config.RegistryConfig
  name: image/tensor_gray_to_rgb
- _target_: atria_registry.registry_config.RegistryConfig
  name: image/normalize
