_target_: atria_transforms.core.sequence.DocumentInstanceTokenizer
tokenizer_name: ???
apply_path: null
task_type: semantic_entity_recognition
init_kwargs: {}
call_kwargs: {}
overflow_sampling: return_all
max_overflow_samples: 10
use_ssl: false
do_normalize: true
do_resize: true
resize_height: 224
resize_width: 224
image_mean: null
image_std: null
