_target_: atria_transforms.core.sequence.DocumentInstanceTokenizer
_partial_: false
tokenizer_name: ???
task_type: semantic_entity_recognition
init_kwargs: null
call_kwargs: null
overflow_sampling: return_all
max_overflow_samples: 10
processor_input_key_map: null
use_ssl: false
do_normalize: true
do_resize: true
resize_height: 224
resize_width: 224
image_mean:
- 0.485
- 0.456
- 0.406
image_std:
- 0.229
- 0.224
- 0.225
